version: '3'
services:
  psp-qr-database:
    container_name: psp-qr-database
    image: postgres
    ports:
      - 5454:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
