services:
  bank-db:
    container_name: bank-db
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname

  bank-backend:
    container_name: bank-backend
    image: fastapi-hot-reload
    command: bash -c "uv run fastapi dev --host 0.0.0.0 --port 9000"
    user: "${UID}:${GID}"
    healthcheck:
      test: curl --fail http://localhost:9000/health || exit 1
      interval: 2s
      timeout: 5s
      retries: 3
      start_period: 3s
    volumes:
      - ./backend:/backend
    working_dir: /backend
    depends_on:
      bank-db:
        condition: service_started
