version: '3'
services:
  telecom-db:
    container_name: telecom-db
    image: postgres
    ports:
      - 5440:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
