services:
  pcc-db:
    container_name: pcc-db
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname

  pcc-backend:
    container_name: pcc-backend
    image: fastapi-hot-reload
    command: bash -c "uv run fastapi dev --port 9000"
    user: "${UID}:${GID}"
    volumes:
      - ./backend:/backend
    working_dir: /backend
    depends_on:
      pcc-db:
        condition: service_started
