services:
  psp-qr-handler-db:
    container_name: psp-qr-handler-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
