services:
  psp-crypto-handler-db:
    container_name: psp-crypto-handler-db
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname

  psp-crypto-handler-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "fastapi dev app/main.py --host 0.0.0.0 --port 9000 --root-path /api/v1"
    user: "${UID}:${GID}"
    healthcheck:
      test: curl --fail http://localhost:9000/health || exit 1
      interval: 2s
      timeout: 5s
      retries: 3
      start_period: 3s
    restart: always
    depends_on:
      psp-crypto-handler-db:
        condition: service_started
    volumes:
      - ./backend/.env:/app/.env:ro
    deploy:
      mode: replicated
      replicas: 6

  psp-crypto-handler-reverse-proxy:
    container_name: psp-crypto-handler-reverse-proxy
    image: nginx
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      psp-crypto-handler-backend:
        condition: service_started
