services:
  psp-crypto-handler-db:
    container_name: psp-crypto-handler-db
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname

  psp-crypto-handler-backend:
    container_name: psp-crypto-handler-backend
    image: fastapi-hot-reload
    command: bash -c "uv run fastapi dev --host 0.0.0.0 --port 9000 --root-path /api/v1"
    user: "${UID}:${GID}"
    volumes:
      - ./backend:/backend
    working_dir: /backend
    depends_on:
      psp-crypto-handler-db:
        condition: service_started

  psp-crypto-handler-reverse-proxy:
    container_name: psp-crypto-handler-reverse-proxy
    image: nginx
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      psp-crypto-handler-backend:
        condition: service_started
