services:
  psp-core-db:
    container_name: psp-core-db
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname

  psp-core-backend:
    container_name: psp-core-backend
    image: fastapi-hot-reload
    command: bash -c "uv run fastapi dev --host 0.0.0.0 --port 9000 --root-path /api/v1"
    user: "${UID}:${GID}"
    healthcheck:
      test: curl --fail http://localhost:9000/health || exit 1
      interval: 2s
      timeout: 5s
      retries: 3
      start_period: 3s
    volumes:
      - ./backend:/backend
    working_dir: /backend
    depends_on:
      psp-core-db:
        condition: service_started
      consul:
        condition: service_started

  psp-core-reverse-proxy:
    container_name: psp-core-reverse-proxy
    image: nginx
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      psp-core-backend:
        condition: service_started

  consul:
    image: hashicorp/consul:1.18
    container_name: consul
    command: agent -dev -ui -client=0.0.0.0 -bind=0.0.0.0
    ports:
      - "8500:8500"         # HTTP API + UI
      - "8600:8600/tcp"     # DNS (TCP)
      - "8600:8600/udp"     # DNS (UDP)
