services:
  psp-core-db:
    container_name: psp-core-db
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname

  psp-core-backend:
    container_name: psp-core-backend
    image: fastapi-hot-reload
    command: bash -c "uv run fastapi dev --port 9000"
    user: "${UID}:${GID}"
    volumes:
      - ./backend:/backend
    working_dir: /backend
    depends_on:
      psp-core-db:
        condition: service_started
