[project]
name = "demo"
version = "0.1.0"
description = "Demo for project functionalities"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "rich>=13.9.4",
]
