services:
  unicredit-bank-db:
    container_name: unicredit-bank-db
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname

  unicredit-bank-backend:
    container_name: unicredit-bank-backend
    image: fastapi-hot-reload
    command: bash -c "uv run fastapi dev --host 0.0.0.0 --port 9000 --root-path /api/v1"
    user: "${UID}:${GID}"
    healthcheck:
      test: curl --fail http://localhost:9000/health || exit 1
      interval: 2s
      timeout: 5s
      retries: 3
      start_period: 3s
    volumes:
      - ./backend:/backend
    working_dir: /backend
    depends_on:
      unicredit-bank-db:
        condition: service_started

  unicredit-bank-reverse-proxy:
    container_name: unicredit-bank-reverse-proxy
    image: nginx
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      unicredit-bank-backend:
        condition: service_started
